# Repository Hygiene & Quality Gates
repos:
  # Code Formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]
  
  # Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  
  # Security: Detect secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--exclude-files', '.*\.lock|.*\.example']
        exclude: .*\.example|.*\.sample|tests/.*
  
  # Local hygiene and quality checks
  - repo: local
    hooks:
      # Architecture: Check file locations
      - id: check-file-location
        name: Check File Location
        entry: uv run python scripts/check_file_location.py
        language: system
        pass_filenames: true
        files: \.py$
        
      # Architecture: Overall compliance
      - id: check-architecture
        name: Check Architecture Compliance
        entry: uv run python scripts/check_architecture.py
        language: system
        always_run: true
        pass_filenames: false
        
      # Security: Custom secrets detection
      - id: detect-custom-secrets
        name: Detect Custom Secrets
        entry: uv run python scripts/detect_secrets.py
        language: system
        pass_filenames: true
        types: [text]
        
      # Code Quality: No wildcard imports
      - id: check-imports
        name: Check Import Statements
        entry: uv run python scripts/check_imports.py
        language: system
        pass_filenames: true
        files: \.py$
        
      # Code Quality: No print in production
      - id: check-print
        name: Check Print Statements
        entry: uv run python scripts/check_print.py
        language: system
        pass_filenames: true
        files: \.py$
        exclude: ^(scripts|tests|bin)/
        
      # Documentation: Track TODOs (warning only)
      - id: track-todos
        name: Track TODOs
        entry: uv run python scripts/track_todos.py
        language: system
        pass_filenames: true
        files: \.py$
        verbose: true
        
      # Testing: Quick validation
      - id: quick-tests
        name: Quick Test Suite
        entry: uv run -m pytest tests/test_quick_validation.py -v
        language: system
        pass_filenames: false
        always_run: true
        
      # Performance: Regression check
      - id: performance-check
        name: Performance Regression Check
        entry: uv run scripts/quick_performance_check.py
        language: system  
        pass_filenames: false
        always_run: true
